version: "3.8"
services:
  postgres-db:
    container_name: starter-db
    image: "postgres" # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: starter_dev
      POSTGRES_PASSWORD: starter_dev
      POSTGRES_DB: starter_dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "6543:5432"